### ISSUE TITLE
Can't resolve '@angular/http'

### ISSUE THREAD

**Issue by fermedina** [Nodonisko/ionic-cache#103]
Hi.

I'm developing an Ionic application with the last version 4.7.1 of Ionic ([release notes](https://ionicframework.com/docs/release-notes)). When I add the CacheModule to `app.module.ts` I get the following error:
```
./node_modules/ionic-cache/dist/cache.service.js
Module not found: Error: Can't resolve '@angular/http'
```

**Comment by GladisonRibeiro** [comment]
Hi,

I got the same mistake,


workaround for publishing:
![image](https://user-images.githubusercontent.com/11618554/62170105-9e606480-b300-11e9-87e1-0b55b5f848b8.png)

**Comment by trajano** [comment]
My workaround until the release is made 
```
npm install --save "git://github.com/Nodonisko/ionic-cache.git#3422a38708228d2626c77363f2d806a91c537f65"
```

**Comment by jing-zhou** [comment]
the reason is that,  angular 8 was supported starting from ionic 4.7.0; with which, '@angular/http' was obsolete and removed .
please see node_modules/@schematics/angular/migrations/update-8/remove-angular-http.js

**Comment by dhimancontact** [comment]
ERROR in ./node_modules/ionic-cache/dist/cache.service.js
[ng] Module not found: Error: Can't resolve '@angular/http' in '/node_modules/ionic-cache/dist'
facing same issue.

**Comment by Nodonisko** [comment]
Please try it with latest version.
