### ISSUE TITLE
Calling clearGroup throws error when cache is disabled

### ISSUE THREAD

**Issue by MeijerM1** [Nodonisko/ionic-cache#118]
Calling the `clearGroup` method will throw a `Cache entry already expired` error when the cache is disabled.
This can be seen in the snippet below:

https://github.com/Nodonisko/ionic-cache/blob/bf3ac5a356e2adea64a58f7faecf1b37a9ad9cce/src/cache.service.ts#L521-L524

Is there a particular reason why this is the case?
I though the point of `disableCache` was to disable the cache without any hassle?

I could understand if you would log the error to the console but throwing enforces me to wrap the function in a try catch which I don't really want to do.

**Comment by WillPoulson** [comment]
Currently all of the cache methods throw and error when the cache is disabled.

Some users would prefer it to be this way so they can handle when the cache is disabled.

**Comment by WillPoulson** [comment]
Closing due to time, if you have a proposed solution please raise this again with the solution
