### ISSUE TITLE
Disabling cache before Storage is ready will result in cache being reenabled

### ISSUE THREAD

**Issue by MeijerM1** [Nodonisko/ionic-cache#119]
Disabling the cache via the `enableCache `method before Ionic Storage is ready will result in the cache being reenabled.

The problem lies in the `loadCache` method called in the constructor which waits for storage to be ready and then enables the cache.
https://github.com/Nodonisko/ionic-cache/blob/bf3ac5a356e2adea64a58f7faecf1b37a9ad9cce/src/cache.service.ts#L69-L77

I believe the `this.cacheEnabled = true; ` line is redundant because `cacheEnabled` is true by default.

As a temporary workaround you can manually wait for Ionic Storage to be ready and then call the `enableCache` method

**Comment by WillPoulson** [comment]
I've resolved this in this huge refactor commit - 9806864a4fe633cf3a55937669d2ee18ffc318ba This will be released in version `6.0.0-next-2` shortly.
