### ISSUE TITLE
Ionic 2 RC0 Support

### ISSUE THREAD

**Issue by danielehrhardt** [Nodonisko/ionic-cache#12]
Hi,
can you update this to Ionic 2 RC0?
Thanks,
Daniel

**Comment by Nodonisko** [comment]
Of course, in few days it will be ready.

**Comment by Nodonisko** [comment]
Solved in v v1.1.0

**Comment by danielehrhardt** [comment]
Awesome Thanks!!

**Comment by Nodonisko** [comment]
Please test, if everything works for you :) I didn't have time to do all tests on devices.
