### ISSUE TITLE
Can't import ionic-cache in Ionic 5 / Angular 11 project due to change in @ionic/storage lib.

### ISSUE THREAD

**Issue by ghost** [Nodonisko/ionic-cache#126]
Can't import ionic-cache in Ionic 5 / Angular 11 project due to change in @ionic/storage lib.

It seems that IonicStorageModule is no more a member of `@ionic/storage` in angular but need to come from `@ionic/storage-angular`

I had to change it manually in the node-modules.

`
[ng] Compiling ionic-cache : module as esm5
[ng] Error: Failed to compile entry-point ionic-cache (`module` as esm5) due to compilation errors:
[ng] node_modules/ionic-cache/dist/cache.module.js:31:30 - error NG1010: Value at position 0 in the NgModule.imports of CacheModule is not a reference
[ng]   Value could not be determined statically.
[ng]  31                     imports: [
[ng]                                  ~
[ng]  32                         IonicStorageModule.forRoot({
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] ... 
[ng]  35                         })
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]  36                     ]
[ng]     ~~~~~~~~~~~~~~~~~~~~~
[ng]   node_modules/ionic-cache/dist/cache.module.js:32:25
[ng]     32                         IonicStorageModule.forRoot({
[ng]                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]     Unable to evaluate this expression statically.
[ng]   node_modules/ionic-cache/dist/cache.module.js:32:25
[ng]     32                         IonicStorageModule.forRoot({
[ng]                                ~~~~~~~~~~~~~~~~~~
[ng]     Unknown reference.
[ng] Compiling ionic-cache : module as esm5
[ng] An unhandled exception occurred: Failed to compile entry-point ionic-cache (`module` as esm5) due to compilation errors:
[ng] node_modules/ionic-cache/dist/cache.module.js:31:30 - error NG1010: Value at position 0 in the NgModule.imports of CacheModule is not a reference
[ng]   Value could not be determined statically.
[ng]  31                     imports: [
[ng]                                  ~
[ng]  32                         IonicStorageModule.forRoot({
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] ... 
[ng]  35                         })
[ng]     ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]  36                     ]
[ng]     ~~~~~~~~~~~~~~~~~~~~~
[ng]   node_modules/ionic-cache/dist/cache.module.js:32:25
[ng]     32                         IonicStorageModule.forRoot({
[ng]                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]     Unable to evaluate this expression statically.
[ng]   node_modules/ionic-cache/dist/cache.module.js:32:25
[ng]     32                         IonicStorageModule.forRoot({
[ng]                                ~~~~~~~~~~~~~~~~~~
[ng]     Unknown reference.
`

**Comment by dchedufa** [comment]
I got the same issue, any fix?

**Comment by lincolnthree** [comment]
@dchedufa I copied this project into our sources directly and updated the references. Small lib, sucks to do it, probably should send a PR but so busy...

**Comment by cyber-greg** [comment]
I used https://www.npmjs.com/package/patch-package to directly patch the lib at npm install.
and add this in my package.json :

>  "scripts": {
>         "ng": "ng",
>          **_"postinstall": "npx patch-package && ngcc"_**,
>          "start": "ng serve",
>           "build": "ng build",

**Comment by Nodonisko** [comment]
Solved.
