### ISSUE TITLE
Add cordova plugin support

### ISSUE THREAD

**Issue by Nodonisko** [Nodonisko/ionic-cache#13]
Add support for cordova sqllite plugin.

**Comment by nikoTM** [comment]
[This](https://gist.github.com/aggarwalankush/0b700328e797e22a1d9994cb35afdf09) might help.

**Comment by Nodonisko** [comment]
Wow, thanks it will help me a lot!

**Comment by nikoTM** [comment]
Just a note, WebSQL is deprecated and being removed slowly, you will need better error handling there.

**Comment by Nodonisko** [comment]
I know, WebSQL should be used only when you debugging app in browser. On device cordova SQLlite plugin will be used.

**Comment by YasirPanjsheri** [comment]
Hi, I also didn't understand this part `Add cordova-sqlite-storage plugin support again` 
does it mean we have to initialize a database... isn't it already been done in `cache.service.ts`
I followed the instruction... its working while im testing live on device with chromeDev... but when I install the apk , on startup the app crashes `Unfortunately app stopped working`

**Comment by Nodonisko** [comment]
It use browser API for WebSQL, there is also Cordova plugin that do same thing but "more native".

**Comment by YasirPanjsheri** [comment]
So is this the reason why it doesn't work.... ?

**Comment by Nodonisko** [comment]
No, it should work on all devices now. Did it throw any error before crash?

**Comment by YasirPanjsheri** [comment]
No. The app builds fine as I said... But crashes on startup. Not to forget to mention that i am also using ionic storage... Im not sure if there is a conflict/ problem in that regard. I tested when running the app with device connected chromdev console and it was fine.. but with apk nope... I logcat...please see this http://stackoverflow.com/questions/42324113/app-stops-working-after-adding-cordova-sqlite

**Comment by Nodonisko** [comment]
Did you tried it without Cordova sqllite? maybe it crash because of this plugin, not because of Ionic cache lib
