### ISSUE TITLE
NPM package unsync

### ISSUE THREAD

**Issue by personalrad** [Nodonisko/ionic-cache#131]
Hi. I thing npm repository package, instead been last version, doesn't reflect the last code from this git.
I have to clone this repo and npm install as local package to got the last version files and been able to run with angular 12

**Comment by WillPoulson** [comment]
Hi, apologies for this, we're currently in the process of updating the library.

For now you can install the `next` version with `npm install ionic-cache@next` which will work with Angular 12 :) 

I'm going to be releasing this update very shortly

**Comment by Nodonisko** [comment]
6.0.0 released :)
