### ISSUE TITLE
keyPrefix ignored in v6+

### ISSUE THREAD

**Issue by florianguillaumin** [Nodonisko/ionic-cache#132]
Hello 👋

I tried upgrading to 6+ and it seems the keyPrefix is ignored.

I declare the module in app.module.ts as:
```
CacheModule.forRoot({ keyPrefix: 'rest-cache' }),
```

When looking at the IndexedDB in Chrome Dev Tools, every cached item is prefixed with "undefined".

I rollbacked to Ionic-Cache 5, and every item is prefixed with "rest-cache", as expected.

No matter what prefix I use, it is ignored. I also tried to not using a prefix, and the data in IndexedDB is still prefixed with "undefined".

Between every test, I cleared the IndexedDB with Chrome Dev Tools.

**Comment by WillPoulson** [comment]
Hi, thanks for reporting this issue. I'll take a look at it shortly and see if I can resolve this 👍

**Comment by WillPoulson** [comment]
Should be resolved by b43c3ade68f4ec9ae9e22ad2fa8b7baedb14ea83 .

I've just released this fix as `6.0.3` please update and try again 😄

**Comment by florianguillaumin** [comment]
I confirm it now works as expected 👍
Thanks!
