### ISSUE TITLE
Compatible ionic version.

### ISSUE THREAD

**Issue by Remonell** [Nodonisko/ionic-cache#134]
What is the latest ionic version this has been tested with? In general, how can I find out with what version of other packages this is compatible?

**Comment by WillPoulson** [comment]
Hi @Remonell.

This package is compatible with all versions of `@ionic/storage-angular` greater than 3.
And all versions of `@angular/core` greater than 9.

This can be checked in the projects package.json under `peerDependencies` - https://github.com/Nodonisko/ionic-cache/blob/master/projects/ionic-cache/package.json
