### ISSUE TITLE
Cannot include in karma-jasmine unit test project

### ISSUE THREAD

**Issue by felixpes** [Nodonisko/ionic-cache#14]
Can you please advise on how to integrate the project into karma-jasmine unit test?
The project does not contain bundles/*.umd.js file.

Getting the: 
WARN [web-server]: 404: /base/ionic-cache/ionic-cache 

Thanks

**Comment by Nodonisko** [comment]
We still don't have working tests, but i hope it will be ready soon. Sorry for inconvenience.

**Comment by felixpes** [comment]
Thanks. It would be nice to have a UMD file.

Currently you can integrate it to the karma project as follows:

In **karma-test-shim.js**:

```
System.config(
{
  paths: {
    . . .
    // paths serve as alias
    'npm:': 'node_modules/',
  },

map: {
    . . .
    'ionic-cache': 'npm:ionic-cache',
     
},

packages: {
   . . .
    'ionic-cache': {
          defaultExtension: 'js'
     },
 }
```


In **karma-conf.js**

```
files: [ 
          . . .
    //ionic-cache
      {pattern: 'node_modules/ionic-cache/**/*.js', included: false, watched: false}
    ],
```

**Comment by Nodonisko** [comment]
Ok, thank you for info!
