### ISSUE TITLE
SQL error when caching response containing an apostrophe 

### ISSUE THREAD

**Issue by felixpes** [Nodonisko/ionic-cache#15]
SQL error when caching response containing an apostrophe (')

**Comment by Nodonisko** [comment]
Thanks for reporting, it will fix it soon.

**Comment by tushar-velingkar** [comment]
Has this issue been fixed?? I am facing the same issue.

**Comment by Nodonisko** [comment]
I am on holiday now, but i will commit hotfix at the beggining of January
and new version with lot of features will follow soon.
Dne 27. 12. 2016 5:24 "tushar-velingkar" <notifications@github.com>
napsal(a):

**Comment by Nodonisko** [comment]
Fixed in latest version 1.1.1.
