### ISSUE TITLE
Cache loading inconsistent in browser

### ISSUE THREAD

**Issue by Captnwalker1** [Nodonisko/ionic-cache#21]
I know this is probably more of a "nice to have" than a must. But I've noticed when using the browser to test the loading times from cache can be up to 10-20 seconds sometimes without making an external call. Other times it is fast as a device. Where on a device it is always consistently fast.

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002

And browser I am testing in Chrome(Version 56.0.2924.87 (64-bit)) with device emulation in dev tools emulating both Galaxy S5 or iPhone 6 usually.

**Comment by Nodonisko** [comment]
Very strange issue, did you tried any other version of Chrome? Maybe it could be related to this specific version...

**Comment by Nodonisko** [comment]
Should be fixed by #29
