### ISSUE TITLE
.isOnline() inconsistent result

### ISSUE THREAD

**Issue by XPanniX** [Nodonisko/ionic-cache#23]
I tried connecting my phone via WiFi and mobile data but most of the time .isOnline() returns false.
Only once it returned true and I can't tell why. 
Any idea why this happens?

**Comment by XPanniX** [comment]
Tried it on OnePlus 3 running Android 7

**Comment by Nodonisko** [comment]
It using this [window online and offline events](https://developer.mozilla.org/en/docs/Online_and_offline_events). Can you can try access this directly and compare it with .isOnline() results?

**Comment by XPanniX** [comment]
Always returns false.
I installed `cordova-plugin-network-information` and if this is installed I get the correct values. Is this a dependency I missed?

**Comment by Nodonisko** [comment]
This plugin is not used by service, I think you should turn offline invalidation off for now.

**Comment by XPanniX** [comment]
I wanted to use the offline check to only return data from cache, if the device is offline.

By the way, is there a way to set the TTL so that an item never expires (e.g. setting TTL to -1 or something)?

**Comment by Nodonisko** [comment]
There is no feature for that, but PR is welcome :)

**Comment by WillPoulson** [comment]
Closing as I've implemented the changes @bpfrare made in fc69a79c80d11f5a053ae28d7c8b61155f6eb4bc and added him as a contributor. This will be released in `6.0.0-next-2` shortly.
