### ISSUE TITLE
Uncaught (in promise): No such key: http://ip.jsontest.com

### ISSUE THREAD

**Issue by gudeidea** [Nodonisko/ionic-cache#26]
Hello!

I'm trying to make the Cache request and this error pops up.
"Runtime Error
Uncaught (in promise): No such key: http://ip.jsontest.com"

What I'm doing wrong?

Thanks!

**Comment by Nodonisko** [comment]
Did you this.cache.saveItem(key, result) before?

**Comment by Nodonisko** [comment]
This should work in latest version.
