### ISSUE TITLE
Observable error handling

### ISSUE THREAD

**Issue by ricardo-mello** [Nodonisko/ionic-cache#34]
Hey guys, I can't catch http errors when using `loadFromObservable`.

Here is my provider method:

```typescript
test() {
  let request = this.http.get(this.API_URL)
    .timeout(20000)
    .map(resp => resp.json());

  return this.cache.loadFromObservable(this.API_URL, request);
}
```

In my component I call:

```typescript
this.myProvider.test().subscribe(
    data => console.log('cool'),
    error=> console.log('not cool')
  );
```

When any http error is thrown, none of them is fired.

**Comment by Nodonisko** [comment]
Thanks for reporting, yes it's bug... I will try to fix it soon as possible or PR is welcome :)

**Comment by ricardo-mello** [comment]
@Nodonisko I found a workaround here. I will submit a PR so you can validate.
