### ISSUE TITLE
Possible to save 17MB?

### ISSUE THREAD

**Issue by Taewa** [Nodonisko/ionic-cache#38]
Hi all.
I am using ionic 3 and I want to save 17MB json data in the local.
First, I thought using local storage but the limit in mobile is 5MB :(
So I ended up here.

I am wondering if this plugin fits with my demand. Is there a page that I can check limit of storage ?

Thank you.

**Comment by Nodonisko** [comment]
Hi,
use Ionic Storage with SQLLite directly https://ionicframework.com/docs/storage/

**Comment by Taewa** [comment]
@Nodonisko Thank you very much! I will try it!

**Comment by Nodonisko** [comment]
You're welcome.
