### ISSUE TITLE
no such key

### ISSUE THREAD

**Issue by watermelon-brother** [Nodonisko/ionic-cache#40]
hi!
I use the function which is the  loadFromObservable in ionic3.it cause a error when run.
error:
Uncaught (in promise): No such key: http://ip.jsontest.com

my function(it's your demo,why?)
loadList() {
    let url = "http://ip.jsontest.com";
    let cacheKey = url;
    let request = this.http.get(url).map(res => res.json());

    return this.cache.loadFromObservable(cacheKey, request);
  }

**Comment by Nodonisko** [comment]
It's definitely bug, can you provide information about browser you use, device etc.?

**Comment by watermelon-brother** [comment]
now!everything is ok!
the tools is very good!think you! hope you can keep update with the ionic !@Nodonisko

**Comment by Alberick0** [comment]
I get this when there's nothing on the cache, I have a calendar page and when I load it, inside my ionViewDidLoad I call my api service which retrieves all the events that's when I get the 'no such key'

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by watermelon-brother** [comment]
you can use like this
this.cache.loadFromObservable(cacheKey, request).subscribe(); @Alberick0

**Comment by D4rkMindz** [comment]
Same problem here. If the cache-item is empty, there is the message, that there is no key.

**Comment by harsandevhunt** [comment]
Have to use like this below to overcome this issue,

loadList() {
let url = "http://ip.jsontest.com";
let request = this.http.get(url);

return this.cache.loadFromObservable(url, request).subscript((res:Response) => {res.json()});

**Comment by D4rkMindz** [comment]
try to replace subscript with subscribe
