### ISSUE TITLE
clearGroup not clear

### ISSUE THREAD

**Issue by Gazaret** [Nodonisko/ionic-cache#42]
After the first call clearGroup I noticed that the items are not remotely. So the request is only during the second attempt.

**Comment by Sampath-Lokuge** [comment]
Yes.It happens me too.Please merge the above pull request.Thanks.

**Comment by Sampath-Lokuge** [comment]
@Gazaret Can you please tell me how to use your above fix with my application?

**Comment by Sampath-Lokuge** [comment]
@Nodonisko Have you updated the `NPM`?

**Comment by Nodonisko** [comment]
Yes, it's 2.0.5

**Comment by Sampath-Lokuge** [comment]
Thank you so much.I'll try it and will let you know @Nodonisko

**Comment by Sampath-Lokuge** [comment]
Yes, Now it is working.Thanks a lot @Gazaret and @Nodonisko  :clap:

**Comment by sannyrss** [comment]
I have installed the latest version but still clearGroup updating in second pull. 

```
	public getPosts(query, pulltorefresh = false) {
		query = this.createRequest(query);
		let url = this.config.webApiUrl + `/allposts?${query}&_embed`;
        let cacheKey = url;
    	let groupKey = cacheKey;

		if(pulltorefresh == true) {
			// Waiting
			this.cache.clearGroup(cacheKey); 
	        let request = this.http.get(url).map(res => res.json());
	        return this.cache.loadFromObservable(cacheKey, request, groupKey);
		} else {
	        let request = this.http.get(url).map(res => res.json());
	        return this.cache.loadFromObservable(cacheKey, request, groupKey);
    	}
	}
```

**Comment by Gazaret** [comment]
clearGroup return Promise. Try this:
```
public async getPosts(query, pulltorefresh = false) {
    query = this.createRequest(query);
    let url = this.config.webApiUrl + `/allposts?${query}&_embed`;
    let cacheKey = url;
    let groupKey = cacheKey;

    if(pulltorefresh == true) {
       await this.cache.clearGroup(cacheKey); 
    }

    let request = this.http.get(url).map(res => res.json());
    return this.cache.loadFromObservable(cacheKey, request, groupKey);
}

**Comment by bergpb** [comment]
Have a exemple with observables? I try to use but cache clear just in second pull refresh.

**Comment by rafaneri** [comment]
I'm with a similar problem on the version 6.0.3.
After clear group cache still getting the old cleared cache value when execute loadFromObservable and anyone call is done in the server.

It is my clear cache call in documentService:
```typescript

  async clearCache() {
    return new Promise((resolve, reject) => {
// here I'm try guarantee that cache is cleared
      this.cache
        .clearGroup(CacheKeys.documents)
        .then((v) => resolve(v))
        .catch((e) => reject(e));
    });
  }

```

In my business the cache is cleared before and then the loader is dismissed.

```typescript
private processDocumentUpload(observable: Observable<any>) {
    observable.toPromise().then(
      () => {
        this.documentService.clearCache().then((v) => this.loader.dismiss());
      },
      async (err) => {
        await this.alertService.alertOk('error', err.message);
        this.loader.dismiss();
      }
    );
  }
```

This video shows the problem:

https://user-images.githubusercontent.com/7685408/139303282-0e12a5dc-8202-4a03-aab7-4cc810b2da54.mp4

**Comment by Sampath-Lokuge** [comment]
@rafaneri Please open a new issue. This is a closed issue and no one will see it again.

**Comment by rafaneri** [comment]
Hello @Sampath-Lokuge it's here #133 

> @rafaneri Please open a new issue. This is a closed issue and no one will see it again.
