### ISSUE TITLE
TypeError: observable.share is not a function

### ISSUE THREAD

**Issue by andplusblaw** [Nodonisko/ionic-cache#47]
I am getting a

TypeError: observable.share is not a function
    at CacheService.loadFromObservable (cache.service.js:240)

and the line points to 
observable = observable.share();

is there something I am missing? that I need to import?

**Comment by andplusblaw** [comment]
found the my problem, sorry

**Comment by PAFleche** [comment]
Hello,
I Got the same issue, can you please tell me how you fixed it ?

Regards,

**Comment by andplusblaw** [comment]
Sure, hopefully it helps

The variable that is receiving whatever comes back from loadFromObservable or loadFromDelayedObservable needs to be a type of Observable. I am using Angular4 with Typescript so I just cast the variable to be a Observable in my class. Something like this.

 public messages: Observable<any>;
