### ISSUE TITLE
Not working in IOS simulator or IOS device but working for android and ionic serve

### ISSUE THREAD

**Issue by sannyrss** [Nodonisko/ionic-cache#48]
Hi,

I have used your plugin in my project and in first phase I created android build and have released and it is working great.

Now, when I am trying to create an IOS build it is not working. I tried IONIC serve and it is coming fine and working good but in IOS simulator and IOS device returning no response and loader never gets terminated.

```
	public getPosts(query, pulltorefresh = false) {
		query = this.transformRequest(query);
		let url = this.config.webApiUrl+ `/webapi?${query}&_embed`;
        let cacheKey = url;
    	let groupKey = cacheKey;
	        let request = this.http.get(url).map(res => res.json());
	        return this.cache.loadFromDelayedObservable(cacheKey, request, groupKey, this.config.cacheTime, delayType);

	}
```

Thanks Sanny

**Comment by sannyrss** [comment]
Anyone can help here? @Nodonisko @imatefx @eesdil @vojtatranta @ricardo-mello @ihadeed

**Comment by imatefx** [comment]
Do you use any specific adapter for storage?

Can you test using Cordova SQLite adapter?

**Comment by eesdil** [comment]
From the query above I cannot see what is the delayType...
Also I suppose you have the latest version of all packages. And as asked before would be good to know the adapter you are using.

**Comment by sannyrss** [comment]
@imatefx  I have tried with local storage as well as with SQLite, both is not working well with this plugin. 

@eesdil  I forgot to copy, let delayType = 'all'; has been defined within the function. 

please help, my build is pending bcz of this issue. 

Thanks Sanny
