### ISSUE TITLE
cache-storage 

### ISSUE THREAD

**Issue by rohitshres** [Nodonisko/ionic-cache#49]
Error: Uncaught (in promise): QuotaExceededError: at c (http://localhost:8100/build/polyfills.js:3:13535) at http://localhost:8100/build/polyfills.js:3:12891 at http://localhost:8100/build/polyfills.js:3:14887 at t.invoke (http://localhost:8100/build/polyfills.js:3:9283) at Object.onInvoke (http://localhost:8100/build/vendor.js:4509:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:9223) at r.run (http://localhost:8100/build/polyfills.js:3:4452) at http://localhost:8100/build/polyfills.js:3:14076 at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967) at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4500:37)

**Comment by Nodonisko** [comment]
Try it with latest version.
