### ISSUE TITLE
Endless TTL

### ISSUE THREAD

**Issue by adyba** [Nodonisko/ionic-cache#54]
I know it looks kinda counterintuitive, but for some purposes (ie. AngularFire authentication) it would be nice to have an immortal cache item. AngularFire has its own TTL and it's gets really messy when those two intervals aren't in sync.  TTL = -1 would do the trick.

**Comment by cocowalla** [comment]
If you set the TTL to `Number.MAX_VALUE`, it will never expire.

OK, *technically* it will expire in around 5.676053e+300 years :)

**Comment by Nodonisko** [comment]
For now I recommend use of very big number, like @cocowalla said.
