### ISSUE TITLE
Angular 5.0 / RxJS 5.5: Lettable operators

### ISSUE THREAD

**Issue by saiy2k** [Nodonisko/ionic-cache#59]
With RxJS 5.5, we need to do imports like

```
import { debounceTime } from 'rxjs/operators/debounceTime';
import { switch } from 'rxjs/operators/switchMap';
```

rather than
```
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/switchMap';
```

More @ https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

An update with this change will be highly appreciated.

**Comment by Nodonisko** [comment]
Solved in latest version.
