### ISSUE TITLE
clearAll() removes everything in ionic Storage

### ISSUE THREAD

**Issue by jaybloke** [Nodonisko/ionic-cache#60]
I'm using ionic storage to store long-term preferences handled by another service and just discovered that clearAll() removes everything from storage - not just those cached entries managed by ionic-cache.

At application start up I want to be able to completely clear the ionic-cache entries without destroying my long-term preferences.

I understand cache groups can be used to handle this case, however I am actually using these as a means to manage related data primarily derived from http get calls.

My workaround is to prefix all my cache keys with 'ionic-cache:<key>' and then iterate over the keys ( this.storage.keys() ) at start up, calling this.storage.remove() to remove the entries one by one from ionic Storage

It would be nice if some kind of root key/prefix could be employed as a configuration option so that I don't have to jump through hoops - basically a call to clearAll() will only destroy cache entries that contain the root key/prefix.

Apart from my little issue, I have to say this is a superb service that everyone should be using in their ionic apps - It circumvents the need to set up and manage caching using those pesky SQLite tables etc.

**Comment by gerhardcit** [comment]
Wow, "clearAll() removes everything from storage", that will destroy my app local storage.. NOT a good idea.

**Comment by Nodonisko** [comment]
We definitely need some prefix for cache items

**Comment by jaybloke** [comment]
Would also be nice to be able to wildcard the removal of cached items e.g. 

`this.cache.removeItem('/projects/1/*');`

This would be very useful since most of the time we are dealing with Rest APIs e.g.

```
GET /projects   -> Cached
GET /projects/1/something  -> Cached
```
Then to simply remove/invalidate the cache when say creating a new project, I could add the invalidation into a http interceptor:

```
if (method = 'POST' && path == '/projects/*') {
  this.cache.removeItem('/projects/*')
}
```

Would lend a hand to implement, but completely snowed under at the moment :-(

**Comment by darthdie** [comment]
I've added the wildcard removal in commit af2ddcd19ec9033821dbae51358089c61447be83

I'm currently thinking through the best way to add some sort of prefix (or similar idea), while maintaining backwards compatibility.

**Comment by darthdie** [comment]
I've added a key prefix in commit 3ea632ec95bf19740af81a793203a1b32a6bc7e7
