### ISSUE TITLE
Feature request: Check if cached item exists without loading the item

### ISSUE THREAD

**Issue by JarmoKukkola** [Nodonisko/ionic-cache#61]
Currently, the only way that I am aware of the know, if a item exists is "getItem()". In some cases, it is only needed to know, whether the item exists. It would be optimal to not load large items, if they are not needed.

**Comment by JarmoKukkola** [comment]
Added a pull request, where I implemented the functionality.

https://github.com/Nodonisko/ionic-cache/pull/62

**Comment by Nodonisko** [comment]
Solved in latest version.
