### ISSUE TITLE
Return expired items  

### ISSUE THREAD

**Issue by alangf** [Nodonisko/ionic-cache#69]
On some cases, I'd rather get an expired item (and attempt to update it on the background) than to do an actual request. Is it possible to implement something like that? I wrote a small service for this, but on this library I guess it would mean a core change (flag on items for wether they should be purged on cleanups or not).

**Comment by Nodonisko** [comment]
@alangf What about `Delayed observable caching`? https://github.com/Nodonisko/ionic-cache#delayed-observable-caching

**Comment by alangf** [comment]
@Nodonisko exactly that, I missed that from the docs, sorry. Closing this.
