### ISSUE TITLE
It  does not work  on android  phone  

### ISSUE THREAD

**Issue by 519818538** [Nodonisko/ionic-cache#70]
It  works  fine   on  chrome.But  i  packaged  to  android apk  ,then  it  does  not  work.

**Comment by Nodonisko** [comment]
@519818538 Can you provide more info? Any error etc.?

**Comment by TheDuc** [comment]
I get 'Uncaught (in promise): QuotaExceededError' on Android.
Maybe that is the same bug as @519818538 had?
I have disabled caching as workaround: `this.cache.enableCache(false);`

**Comment by Nodonisko** [comment]
@TheDuc Do you have free space on your device?

**Comment by 519818538** [comment]
I  have  solved  this  problem.  Because the  Response  headers  cache  between chrome and  android  is  different.

**Comment by TheDuc** [comment]
@Nodonisko Thanks! That was indeed the problem. There was some space (few hunderds MB) left on the device, but apparently not enough.
