### ISSUE TITLE
Support for Ionic 4

### ISSUE THREAD

**Issue by ljieyao** [Nodonisko/ionic-cache#81]

**Comment by ThorvaldAagaard** [comment]
Any plans for supporting Ionic V4. Currently it fails during compilation as it is using an old version of Observables from rsjx

**Comment by ThorvaldAagaard** [comment]
Could probably be solved just by changing 

import { Observable } from 'rxjs/Observable';

to 

import { Observable } from 'rxjs';

in cache.service


or at least it now compiles

**Comment by ramonornela** [comment]
related #83

**Comment by ramonornela** [comment]
close @ljieyao already fix
