### ISSUE TITLE
loadFromDelayedObservable indicate if the data came from cache or network

### ISSUE THREAD

**Issue by joegarb** [Nodonisko/ionic-cache#82]
Would it be possible to indicate whether the data that I receive from loadFromDelayedObservable came from the cache vs. from the network?

In my app I have some logic that really only needs to be run when fresh data has been retrieved from the server. I've made it so that still works fine when it gets triggered multiple times (first with the cached data and second with the server data), but still I'd prefer the code to not be run unnecessarily, and just to be safe in case there could be timing issues.

Thanks!

**Comment by ruisilva450** [comment]
Any news on this being merged to master?

**Comment by Nodonisko** [comment]
@ruisilva450 Merged.

**Comment by ruisilva450** [comment]
@Nodonisko When can we expect this to go live on a new npm version?
