### ISSUE TITLE
CacheService object undefined 

### ISSUE THREAD

**Issue by hizhao** [Nodonisko/ionic-cache#9]
(step1) install the ionic-cache
    ionic plugin add cordova-sqlite-storage
    npm install ionic-cache --save
(step2) usage
...
import {CacheService} from "ionic-cache/ionic-cache";
export class MyApp {
  private rootPage: any;
  pages: Array<{title: string, component: Type}> 
  constructor(private platform: Platform, private menu:MenuController, private app:App,private cache: CacheService ) {
    this.cache = cache;
    console.log(this.cache); // Here this.cache is "undefined" from Chrome console
    ....
}

ionicBootstrap(MyApp, [
  CacheService
]);

-------env info--------------------
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.7 
OS: Mac OS X Yosemite
Node Version: v4.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by hizhao** [comment]
(step1) install the ionic-cache
ionic plugin add cordova-sqlite-storage
npm install ionic-cache --save
(step2) usage
...
import {CacheService} from "ionic-cache/ionic-cache";
export class MyApp {
private rootPage: any;
pages: Array<{title: string, component: Type}> 
constructor(private platform: Platform, private menu:MenuController, private app:App,private cache: CacheService ) {
this.cache = cache;
console.log(this.cache); // Here this.cache is "undefined" from Chrome console
....
}

ionicBootstrap(MyApp, [
CacheService
]);

-------env info--------------------
Cordova CLI: 6.3.0
Gulp version: CLI version 3.9.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.7 
OS: Mac OS X Yosemite
Node Version: v4.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by Nodonisko** [comment]
Delete line "this.cache = cache", TypeScript will do this automatically for you. I will fix it in docs in Friday.
