### ISSUE TITLE
Import issue with version 4.0.0

### ISSUE THREAD

**Issue by niconaso** [Nodonisko/ionic-cache#95]
With version 4.0.0 of ionic-cache, typescript is complaining and throwing this error:

 >Cannot find module 'ionic-cache'.ts (2307)

I think this issue is related with the  "fullTemplateTypeCheck": true flag enabled in the last version.

Can you help me? 
Thanks!

**Comment by darellduma** [comment]
I had the same issue I had to use [@ionic/storage](https://ionicframework.com/docs/building/storage) as an alternative.

**Comment by ramonornela** [comment]
Fixed temoorary: ```"@ammora/ionic-cache": "4.0.0-2"```

**Comment by Nodonisko** [comment]
Fixed in 4.0.1
